launcher.version=1.0.1
manifest.defaultUrl=https://github.com/NilsMod/NilsModLauncher/releases/latest/download/nilsmod-manifest.json
optional.fabricApi=true
optional.sodium=true
optional.simpleVoiceChat=true
